// DO NOT EDIT — This file is generated by OTel Weaver.
// Source: src/weaver/model/attributes.yaml
package com.slct.demo.config;

import io.opentelemetry.api.common.AttributeKey;
import java.util.List;

/**
 * Attributes used to describe media content being queried.
 *
 * <p>Group: {@code registry.media_content}
 */
public final class MediaContentAttributes {
  /**
   * The name of the album containing the song.
   *
   * <p>Examples: Nevermind, In Utero, Bleach, Incesticide.
   */
  public static final AttributeKey<String> ATTR_MEDIA_ALBUM_NAME =
      AttributeKey.stringKey("media.album.name");
  /**
   * The name of the artist performing the song.
   *
   * <p>Examples: Nirvana, Foo Fighters, Linkin Park, Slipknot.
   */
  public static final AttributeKey<String> ATTR_MEDIA_ARTIST_NAME =
      AttributeKey.stringKey("media.artist.name");
  /**
   * The duration of the song in milliseconds.
   *
   * <p>Examples: 301000, 355000, 183000, 391000.
   */
  public static final AttributeKey<Long> ATTR_MEDIA_SONG_DURATION_MS =
      AttributeKey.longKey("media.song.duration_ms");
  /**
   * The musical genre of the song.
   *
   * <p>Examples: Rock, Punk, Grunge, Classical, Hip Hop.
   */
  public static final AttributeKey<String> ATTR_MEDIA_SONG_GENRE =
      AttributeKey.stringKey("media.song.genre");
  /**
   * The name/title of the song being queried.
   *
   * <p>Examples: Smells Like Teen Spirit, Come As You Are, Lithium, Something In The Way.
   */
  public static final AttributeKey<String> ATTR_MEDIA_SONG_NAME =
      AttributeKey.stringKey("media.song.name");
  /**
   * The release year of the song.
   *
   * <p>Examples: 1991, 1975, 1971, 1976.
   */
  public static final AttributeKey<Long> ATTR_MEDIA_SONG_YEAR =
      AttributeKey.longKey("media.song.year");
  private MediaContentAttributes() {}
}
