// DO NOT EDIT — This file is generated by OTel Weaver.
// Source: src/weaver/model/attributes.yaml
//
// Attributes used to describe media content being queried.
/**
 * The name of the album containing the song.
 *
 * @example Nevermind, In Utero, Bleach, Incesticide
 */
const ATTR_MEDIA_ALBUM_NAME = 'media.album.name';
/**
 * The name of the artist performing the song.
 *
 * @example Nirvana, Foo Fighters, Linkin Park, Slipknot
 */
const ATTR_MEDIA_ARTIST_NAME = 'media.artist.name';
/**
 * The duration of the song in milliseconds.
 *
 * @example 301000, 355000, 183000, 391000
 */
const ATTR_MEDIA_SONG_DURATION_MS = 'media.song.duration_ms';
/**
 * The musical genre of the song.
 *
 * @example Rock, Punk, Grunge, Classical, Hip Hop
 */
const ATTR_MEDIA_SONG_GENRE = 'media.song.genre';
/**
 * The name/title of the song being queried.
 *
 * @example Smells Like Teen Spirit, Come As You Are, Lithium, Something In The Way
 */
const ATTR_MEDIA_SONG_NAME = 'media.song.name';
/**
 * The release year of the song.
 *
 * @example 1991, 1975, 1971, 1976
 */
const ATTR_MEDIA_SONG_YEAR = 'media.song.year';

module.exports = {
  ATTR_MEDIA_ALBUM_NAME,
  ATTR_MEDIA_ARTIST_NAME,
  ATTR_MEDIA_SONG_DURATION_MS,
  ATTR_MEDIA_SONG_GENRE,
  ATTR_MEDIA_SONG_NAME,
  ATTR_MEDIA_SONG_YEAR,
};
