name: Daily Renovate

on:
  schedule:
    - cron: '0 0 * * *'  # Run daily at 00:00 UTC
  workflow_dispatch:  # Allow manual trigger

permissions:
  contents: read

jobs:
  renovate:
    name: Renovate
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803  # v6
      - name: Renovate Bot GitHub Action
        uses: renovatebot/github-action@39b914146caeff8cd512e61c8992f1d5913af85c  # v46.2.5
        with:
          configurationFile: renovate.json
          token: ${{ secrets.RENOVATE_TOKEN }}
        env:
          RENOVATE_REPOSITORIES: julianocosta89/kubecon-eu-2026
