extensions:
  healthcheckv2:
    use_v2: true
    component_health:
      include_permanent_errors: false
      include_recoverable_errors: true
      recovery_duration: 5m
    http:
      endpoint: "localhost:13133"
      status:
        enabled: true
        path: "/health/status"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_GRPC}
      http:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_HTTP}

processors:
  resource:
    attributes:
      - key: deployment.environment.name
        value: "dev"
        action: upsert

exporters:
  debug:
#   verbosity: detailed
  otlp_grpc/jaeger:
    endpoint: "http://jaeger:4317"
    tls:
      insecure: true
    sending_queue:
      batch:

service:
  extensions: [healthcheckv2]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [resource]
      exporters: [debug, otlp_grpc/jaeger]
    metrics:
      receivers: [otlp]
      processors: [resource]
      exporters: [debug]
