extensions:
  healthcheckv2:
    use_v2: true
    component_health:
      include_permanent_errors: false
      include_recoverable_errors: true
      recovery_duration: 5m
    http:
      endpoint: "localhost:13133"
      status:
        enabled: true
        path: "/health/status"
  datadog/extension:
    api:
      site: ${DD_SITE_PARAMETER}
      key: ${DD_API_KEY}
    http:
      endpoint: "localhost:9875"
      path: "/metadata"

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_GRPC}
      http:
        endpoint: ${env:OTEL_COLLECTOR_HOST}:${env:OTEL_COLLECTOR_PORT_HTTP}
  docker_stats:
    endpoint: unix:///var/run/docker.sock
    initial_delay: 300s
  hostmetrics:
    root_path: /hostfs
    initial_delay: 300s
    scrapers:
      cpu:
        metrics:
          system.cpu.utilization:
            enabled: true
          system.cpu.logical.count:
            enabled: true
      disk:
      load:
      filesystem:
        exclude_mount_points:
          mount_points:
            - /dev/*
            - /proc/*
            - /sys/*
            - /run/k3s/containerd/*
            - /var/lib/docker/*
            - /var/lib/kubelet/*
            - /snap/*
          match_type: regexp
        exclude_fs_types:
          fs_types:
            - autofs
            - binfmt_misc
            - bpf
            - cgroup2
            - configfs
            - debugfs
            - devpts
            - devtmpfs
            - fusectl
            - hugetlbfs
            - iso9660
            - mqueue
            - nsfs
            - overlay
            - proc
            - procfs
            - pstore
            - rpc_pipefs
            - securityfs
            - selinuxfs
            - squashfs
            - sysfs
            - tracefs
          match_type: strict
      memory:
        metrics:
          system.memory.utilization:
            enabled: true
          system.memory.limit:
            enabled: true
      network:
      paging:
        metrics:
          system.paging.usage:
            enabled: true

      processes:
      process:
        mute_process_exe_error: true
        mute_process_io_error: true
        mute_process_user_error: true
      system:
        metrics:
          system.uptime:
            enabled: true

processors:
  memory_limiter:
    check_interval: 1s
    limit_mib: 1000
  resource:
    attributes:
      - key: deployment.environment.name
        value: "dev"
        action: upsert

connectors:
  datadog/connector:
    traces:
      compute_stats_by_span_kind: true

exporters:
  debug:
  # verbosity: detailed
  datadog:
    traces:
      compute_stats_by_span_kind: true
    api:
      site: ${DD_SITE_PARAMETER}
      key: ${DD_API_KEY}
    sending_queue:
      batch:
        min_size: 10
        max_size: 100
        flush_timeout: 10s
  otlp_grpc/jaeger:
    endpoint: "http://jaeger:4317"
    tls:
      insecure: true
    sending_queue:
      batch:


service:
  extensions: [healthcheckv2, datadog/extension]
  pipelines:
    traces:
      receivers: [otlp]
      processors: [memory_limiter, resource]
      exporters: [debug, datadog/connector, datadog, otlp_grpc/jaeger]
    metrics:
      receivers: [otlp, datadog/connector, docker_stats, hostmetrics]
      processors: [memory_limiter, resource]
      exporters: [debug, datadog]
    logs:
      receivers: [otlp]
      processors: [memory_limiter, resource]
      exporters: [datadog]
  telemetry:
    metrics:
      readers:
        - periodic:
            exporter:
              otlp:
                protocol: http/protobuf
                endpoint: https://otlp.${DD_SITE_PARAMETER}/v1/metrics
                temporality_preference: delta
                headers:
                  - name: dd-api-key
                    value: ${DD_API_KEY}
                  - name: dd-otel-metric-config
                    value: '{"resource_attributes_as_tags": true}'
